/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Antd: typeof import('./src/components/antd/index.vue')['default']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ATable: typeof import('ant-design-vue/es')['Table']
    Bar: typeof import('./src/components/echarts/bar.vue')['default']
    Child: typeof import('./src/components/switch/child.vue')['default']
    ChildComponent: typeof import('./src/components/computed/ChildComponent.vue')['default']
    Computed: typeof import('./src/components/computed/index.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    CountUpTimer: typeof import('./src/components/time/CountUpTimer.vue')['default']
    CustomModal: typeof import('./src/components/antd/CustomModal.vue')['default']
    Drawer: typeof import('./src/components/antd/drawer.vue')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    Form: typeof import('./src/components/antd/form.vue')['default']
    Icon: typeof import('./src/components/antd/icon.vue')['default']
    LazyLoadGallery: typeof import('./src/components/LazyLoadGallery.vue')['default']
    ListComponent: typeof import('./src/components/ListComponent.vue')['default']
    Modal: typeof import('./src/components/antd/modal.vue')['default']
    ModalComponent: typeof import('./src/components/ModalComponent.vue')['default']
    Pie: typeof import('./src/components/echarts/pie.vue')['default']
    PieCenter: typeof import('./src/components/echarts/pie-center.vue')['default']
    PieCustom: typeof import('./src/components/echarts/pie-custom.vue')['default']
    PieFull: typeof import('./src/components/echarts/pie-full.vue')['default']
    PieLight: typeof import('./src/components/echarts/pie-light.vue')['default']
    PieTwo: typeof import('./src/components/echarts/pie-two.vue')['default']
    Redio: typeof import('./src/components/antd/redio.vue')['default']
    Switch: typeof import('./src/components/switch/index.vue')['default']
    Table: typeof import('./src/components/antd/table.vue')['default']
    TextTag: typeof import('./src/components/TextTag.vue')['default']
    Time: typeof import('./src/components/time/index.vue')['default']
    Timeline: typeof import('./src/components/antd/timeline.vue')['default']
    Tooltip: typeof import('./src/components/antd/tooltip.vue')['default']
    TooltipMultiple: typeof import('./src/components/TooltipMultiple.vue')['default']
    TooltipMultipleApp: typeof import('./src/components/TooltipMultipleApp.vue')['default']
    Vue3CountTo: typeof import('./src/components/vue3-count-to.vue')['default']
  }
}
