/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AModal: typeof import('ant-design-vue/es')['Modal']
    Ant: typeof import('./src/components/antd/Ant.vue')['default']
    Antd: typeof import('./src/components/antd/index.vue')['default']
    AntIcon: typeof import('./src/components/antd/AntIcon.vue')['default']
    AntModal: typeof import('./src/components/antd/AntModal.vue')['default']
    AntRedio: typeof import('./src/components/antd/AntRedio.vue')['default']
    AntTable: typeof import('./src/components/antd/AntTable.vue')['default']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    AStep: typeof import('ant-design-vue/es')['Step']
    ATable: typeof import('ant-design-vue/es')['Table']
    Bar: typeof import('./src/components/echarts/bar.vue')['default']
    BingApp: typeof import('./src/components/BingApp.vue')['default']
    Child: typeof import('./src/components/switch/child.vue')['default']
    copy: typeof import('./src/components/echarts/pie-full copy.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    CustomModal: typeof import('./src/components/antd/CustomModal.vue')['default']
    EchartsApp: typeof import('./src/components/EchartsApp.vue')['default']
    EchartsApp2: typeof import('./src/components/EchartsApp2.vue')['default']
    EchartsApp3: typeof import('./src/components/EchartsApp3.vue')['default']
    EchartsApp4: typeof import('./src/components/EchartsApp4.vue')['default']
    EchartsApp5: typeof import('./src/components/EchartsApp5.vue')['default']
    Icon: typeof import('./src/components/antd/icon.vue')['default']
    LazyLoadGallery: typeof import('./src/components/LazyLoadGallery.vue')['default']
    ListComponent: typeof import('./src/components/ListComponent.vue')['default']
    Modal: typeof import('./src/components/antd/modal.vue')['default']
    ModalComponent: typeof import('./src/components/ModalComponent.vue')['default']
    Pie: typeof import('./src/components/echarts/pie.vue')['default']
    PieCustom: typeof import('./src/components/echarts/pie-custom.vue')['default']
    PieFull: typeof import('./src/components/echarts/pie-full.vue')['default']
    PieLess: typeof import('./src/components/echarts/pie-less.vue')['default']
    PieLight: typeof import('./src/components/echarts/pie-light.vue')['default']
    Redio: typeof import('./src/components/antd/redio.vue')['default']
    Switch: typeof import('./src/components/switch/index.vue')['default']
    Table: typeof import('./src/components/antd/table.vue')['default']
  }
}
